/*
[CONTEST / EVIDENCE NOTE - Generated by Generative AI]
- 이 파일의 초기 코드(구조/로직/문구)는 생성형 AI(예: ChatGPT)의 도움으로 작성되었습니다.
- 사용자는 "포켓몬 스타일 8비트 RPG 웹플레이형" 요구사항을 프롬프트로 제공했으며,
  본 코드는 그 요구사항(3스테이지 CXJ 배틀, 1/2/3 선택, 정답/오답 처리,
  하단 대사창 UI, 이미지 없는 placeholder, 함수형 구조)을 충족하도록 구성했습니다.

증빙 권장:
1) 프롬프트 원문(PROMPTS.md)에 기록
2) GitHub 커밋 로그 캡처
3) GitHub Pages 배포 링크
4) 실행 화면(브라우저) 캡처
*/

const el = {
  name: document.getElementById("name"),
  text: document.getElementById("text"),
  choices: document.getElementById("choices"),
  stageTitle: document.getElementById("stageTitle"),
  stageSub: document.getElementById("stageSub"),
  banner: document.getElementById("banner"),
  spriteLeader: document.getElementById("spriteLeader"),
  spriteTrainer: document.getElementById("spriteTrainer"),
  footHint: document.getElementById("footHint"),
  btnEnter: document.getElementById("btnEnter"),
  btnR: document.getElementById("btnR"),
};

// ===== 데이터 (여기만 바꾸면 기획 변경 쉬움) =====
const INTRO = [
  { speaker: "이사님", text: "어서 와. 신입 트레이너." },
  { speaker: "이사님", text: "이번 미션은 '기아 딜러십 CXJ 마스터'다." },
  { speaker: "이사님", text: "포켓몬 배틀처럼 질문이 나오면 1~3번으로 선택해." },
  { speaker: "이사님", text: "정답이면… '효과는 굉장했다!' 다음 스테이지로 간다." },
  { speaker: "이사님", text: "오답이면… '고객이 떠났습니다…' 게임 오버다." },
  { speaker: "이사님", text: "준비됐나? Enter를 눌러 시작해." },
];

const STAGES = [
  {
    title: "STAGE 1 - Research / Visit",
    sub: "방문 및 상담 - 안내데스크 응대",
    q: "안내데스크 첫 응대에서 가장 먼저 해야 할 것은?",
    options: [
      "① 대기 중인 고객에게 말을 걸지 않고 기다린다",
      "② 고객의 방문 목적을 확인하고 다음 프로세스를 안내한다",
      "③ 가격표와 프로모션 안내문만 건넨다",
    ],
    correct: 1, // 0-based
  },
  {
    title: "STAGE 2 - Purchase / Contract",
    sub: "견적 및 계약 - 고객 니즈 파악",
    q: "견적/계약 단계에서 고객 니즈 파악의 핵심은?",
    options: [
      "① 최저가만 강조하고 빠르게 계약을 유도한다",
      "② 사용 목적/예산/우선순위를 확인해 맞춤 제안한다",
      "③ 인기 트림만 추천하고 설명은 생략한다",
    ],
    correct: 1,
  },
  {
    title: "STAGE 3 - Ownership / Service",
    sub: "사후 관리 및 정기점검 - 경고등 대응",
    q: "경고등 문의가 들어왔을 때 가장 바람직한 대응은?",
    options: [
      "① 원인 확인 없이 '계속 운행해도 된다'고 답한다",
      "② 증상 확인 후 안전 안내 + 예약/긴급 조치를 연결한다",
      "③ 서비스센터 위치 링크만 던진다",
    ],
    correct: 1,
  },
];

const MSG = {
  correct: "효과는 굉장했다!",
  wrong: "고객이 떠났습니다...",
  clear: "축하합니다! CXJ 마스터 미션 클리어!",
};

// ===== 상태 (함수형으로 관리) =====
function initialState() {
  return {
    mode: "INTRO",      // INTRO | STAGE | FEEDBACK | GAME_OVER | CLEAR
    introIdx: 0,
    stageIdx: 0,
    awaitingChoice: false,
    lastResult: null,   // true/false
    feedbackText: "",
  };
}

let state = initialState();

// ===== 유틸 =====
function showBanner(text, kind) {
  el.banner.textContent = text;
  el.banner.classList.remove("hidden");
  el.banner.style.color = kind === "good" ? "var(--good)" : kind === "bad" ? "var(--bad)" : "var(--text)";
  setTimeout(() => el.banner.classList.add("hidden"), 900);
}

function setSprites(mode) {
  // INTRO/FEEDBACK: 리더 중심, STAGE: 트레이너 중심(배틀 느낌)
  if (mode === "STAGE") {
    el.spriteLeader.classList.add("hidden");
    el.spriteTrainer.classList.remove("hidden");
  } else if (mode === "INTRO") {
    el.spriteLeader.classList.remove("hidden");
    el.spriteTrainer.classList.add("hidden");
  } else {
    el.spriteLeader.classList.remove("hidden");
    el.spriteTrainer.classList.remove("hidden");
  }
}

function clearChoices() {
  el.choices.innerHTML = "";
}

function renderChoices(options, enabled = true) {
  clearChoices();
  options.forEach((txt, i) => {
    const b = document.createElement("button");
    b.className = "choiceBtn";
    b.textContent = txt;
    b.disabled = !enabled;
    b.addEventListener("click", () => choose(i));
    el.choices.appendChild(b);
  });
}

function setUICommon() {
  el.btnR.style.display = "inline-block";
  el.btnEnter.style.display = "inline-block";
}

// ===== 렌더 =====
function render() {
  setUICommon();
  setSprites(state.mode);

  if (state.mode === "INTRO") {
    const line = INTRO[state.introIdx];
    el.stageTitle.textContent = "INTRO";
    el.stageSub.textContent = "Onboarding - Mission Briefing";
    el.name.textContent = line.speaker;
    el.text.textContent = line.text;
    clearChoices();
    el.footHint.textContent = "Enter: 다음";
    return;
  }

  if (state.mode === "STAGE") {
    const st = STAGES[state.stageIdx];
    el.stageTitle.textContent = st.title;
    el.stageSub.textContent = st.sub;
    el.name.textContent = "CXJ 배틀";
    el.text.textContent = st.q;
    renderChoices(st.options, true);
    el.footHint.textContent = "1/2/3 키 또는 버튼 클릭으로 선택";
    return;
  }

  if (state.mode === "FEEDBACK") {
    const st = STAGES[Math.min(state.stageIdx, STAGES.length - 1)];
    el.stageTitle.textContent = st ? st.title : "RESULT";
    el.stageSub.textContent = st ? st.sub : "";
    el.name.textContent = "SYSTEM";
    el.text.textContent = state.feedbackText;
    clearChoices();
    el.footHint.textContent = "Enter: 계속";
    return;
  }

  if (state.mode === "GAME_OVER") {
    el.stageTitle.textContent = "GAME OVER";
    el.stageSub.textContent = "Customer Lost";
    el.name.textContent = "SYSTEM";
    el.text.textContent = `${MSG.wrong}\n\nR을 눌러 처음부터 다시 도전하세요.`;
    clearChoices();
    el.footHint.textContent = "R: 재시작";
    return;
  }

  if (state.mode === "CLEAR") {
    el.stageTitle.textContent = "CLEAR!";
    el.stageSub.textContent = "CXJ Master";
    el.name.textContent = "SYSTEM";
    el.text.textContent = `${MSG.clear}\n\nR을 눌러 다시 플레이하거나, 창을 닫아 종료하세요.`;
    clearChoices();
    el.footHint.textContent = "R: 재시작";
    return;
  }
}

// ===== 진행 로직 =====
function next() {
  if (state.mode === "INTRO") {
    state.introIdx += 1;
    if (state.introIdx >= INTRO.length) {
      state.mode = "STAGE";
      state.awaitingChoice = true;
    }
    render();
    return;
  }

  if (state.mode === "FEEDBACK") {
    if (state.lastResult === true) {
      state.stageIdx += 1;
      if (state.stageIdx >= STAGES.length) {
        state.mode = "CLEAR";
      } else {
        state.mode = "STAGE";
        state.awaitingChoice = true;
      }
    } else {
      state.mode = "GAME_OVER";
    }
    render();
    return;
  }

  // STAGE에서는 Enter로 넘어가지 않음(선택해야 함)
}

function choose(optionIdx) {
  if (state.mode !== "STAGE") return;
  const st = STAGES[state.stageIdx];

  const isCorrect = optionIdx === st.correct;
  state.mode = "FEEDBACK";
  state.lastResult = isCorrect;
  state.feedbackText = isCorrect ? MSG.correct : MSG.wrong;

  showBanner(state.feedbackText, isCorrect ? "good" : "bad");
  render();
}

function restart() {
  state = initialState();
  render();
}

// ===== 이벤트 =====
el.btnEnter.addEventListener("click", next);
el.btnR.addEventListener("click", restart);

window.addEventListener("keydown", (e) => {
  const k = e.key.toLowerCase();

  if (k === "enter" || k === " ") next();
  if (k === "r") restart();

  if (state.mode === "STAGE") {
    if (k === "1") choose(0);
    if (k === "2") choose(1);
    if (k === "3") choose(2);
  }
});

// Start
render();
