"""
KIA Dealership CXJ Quest (Pokemon-style 8-bit mini RPG) - Single File Pygame

──────────────────────────────────────────────────────────────────────────────
[CONTEST / EVIDENCE NOTE - Generated by Generative AI]
- This Python code was generated with the assistance of a generative AI model
  (ChatGPT, OpenAI). The user provided a prompt specifying:
  * Pygame single-file implementation
  * Pokemon-like dialogue box UI
  * 3 stages (Research/Visit, Purchase/Contract, Ownership/Service)
  * 3 choices per stage selectable by keyboard 1/2/3
  * Correct -> "효과는 굉장했다!" -> next stage
  * Wrong -> "고객이 떠났습니다..." -> Game Over
  * No external images required; placeholders (colored boxes/text) used
  * Functional (non-OOP) structure for readability

To prove authorship:
- Keep screenshots of:
  1) your prompt (as provided)
  2) this file content (showing this header)
  3) execution screen showing the game running
  4) your Git commit history (optional if you push to GitHub)

──────────────────────────────────────────────────────────────────────────────
HOW TO RUN
1) Install Python 3.10+ (recommended)
2) Install pygame:
   pip install pygame
3) Run:
   python kia_cxj_quest.py

Controls:
- ENTER / SPACE : Advance dialogue / continue
- 1 / 2 / 3     : Choose an option when presented
- R             : Restart (from intro) on GAME OVER or CLEAR screen
- ESC / Close   : Quit

ASSET PLACEHOLDERS:
- Character and background are drawn as colored rectangles + labels.
- If you later want to use images, search "TODO: IMAGE PLACEHOLDER" markers.
"""

import sys
import pygame

# =========================
# Basic Config
# =========================
WIDTH, HEIGHT = 960, 540
FPS = 60

# Retro-ish palette (you can tweak)
COLOR_BG = (18, 24, 20)         # dark green-ish
COLOR_STAGE = (26, 34, 30)      # slightly lighter
COLOR_BOX = (12, 14, 18)        # dialogue box
COLOR_BORDER = (120, 140, 130)  # muted border
COLOR_TEXT = (230, 240, 235)    # off-white
COLOR_MUTED = (170, 190, 180)   # grey-ish
COLOR_GOOD = (120, 220, 170)
COLOR_BAD = (240, 120, 120)

DIALOGUE_H = 170
PADDING = 18

# =========================
# Game Script Data
# =========================
INTRO_LINES = [
    ("이사님", "어서 와. 신입 트레이너."),
    ("이사님", "이번 미션은 '기아 딜러십 CXJ 마스터'다."),
    ("이사님", "포켓몬 배틀처럼 질문이 나오면 1~3번으로 선택해."),
    ("이사님", "정답이면... 효과는 굉장했다! 다음 스테이지로 간다."),
    ("이사님", "오답이면... 고객이 떠났습니다... 게임 오버다."),
    ("이사님", "좋아. 준비됐나? (ENTER)"),
]

STAGES = [
    {
        "title": "STAGE 1 - Research / Visit",
        "subtitle": "방문 및 상담 - 안내데스크 응대",
        "question": "안내데스크 첫 응대에서 가장 먼저 해야 할 것은?",
        "choices": [
            "대기 중인 고객에게 말을 걸지 않고 기다린다",
            "고객의 방문 목적을 빠르게 확인하고 다음 프로세스를 안내한다",
            "가격표와 프로모션 안내문만 건넨다",
        ],
        "correct_index": 1,
    },
    {
        "title": "STAGE 2 - Purchase / Contract",
        "subtitle": "견적 및 계약 - 고객 니즈 파악",
        "question": "견적/계약 단계에서 고객 니즈 파악의 핵심은?",
        "choices": [
            "최저가만 강조하고 빠르게 계약을 유도한다",
            "고객의 사용 목적/예산/우선순위를 확인해 옵션과 금융을 맞춤 제안한다",
            "인기 트림만 추천하고 설명은 생략한다",
        ],
        "correct_index": 1,
    },
    {
        "title": "STAGE 3 - Ownership / Service",
        "subtitle": "사후 관리 및 정기점검 - 경고등 대응",
        "question": "경고등 문의가 들어왔을 때 가장 바람직한 대응은?",
        "choices": [
            "원인 확인 없이 '계속 운행해도 된다'고 답한다",
            "증상/상황을 확인하고 안전 안내 후 예약/긴급 조치를 연결한다",
            "서비스센터 위치 링크만 던진다",
        ],
        "correct_index": 1,
    },
]

MSG_CORRECT = "효과는 굉장했다!"
MSG_WRONG = "고객이 떠났습니다..."
MSG_CLEAR = "축하합니다! CXJ 마스터 미션 클리어!"

# =========================
# Helpers: Text Rendering
# =========================
def load_fonts():
    """
    Load fonts with fallbacks.
    For a more 8-bit look, you can later ship a pixel TTF and load it here.
    """
    # NOTE: pygame's default font is okay; we simulate retro through layout/colors.
    base = pygame.font.Font(None, 28)
    small = pygame.font.Font(None, 22)
    big = pygame.font.Font(None, 36)
    return base, small, big

def wrap_text(text, font, max_width):
    """Simple word-wrapping (Korean spacing is variable; this still works decently)."""
    words = text.split(" ")
    if not words:
        return [""]

    lines = []
    current = words[0]
    for w in words[1:]:
        test = current + " " + w
        if font.size(test)[0] <= max_width:
            current = test
        else:
            lines.append(current)
            current = w
    lines.append(current)
    return lines

def draw_box(surface, rect, fill, border, border_thickness=3, radius=12):
    pygame.draw.rect(surface, fill, rect, border_radius=radius)
    pygame.draw.rect(surface, border, rect, width=border_thickness, border_radius=radius)

def draw_text_lines(surface, lines, font, color, x, y, line_gap=6):
    yy = y
    for line in lines:
        img = font.render(line, True, color)
        surface.blit(img, (x, yy))
        yy += img.get_height() + line_gap

# =========================
# Placeholder Graphics
# =========================
def draw_scene_placeholders(screen, stage_title, stage_subtitle, show_leader, show_trainer):
    """
    Draws the upper gameplay area with placeholder "sprites" and a background.
    Replace these with images later if you want.

    TODO: IMAGE PLACEHOLDER
    - Replace rectangles with loaded images:
      leader_img = pygame.image.load("assets/leader.png").convert_alpha()
      trainer_img = pygame.image.load("assets/trainer.png").convert_alpha()
      bg_img = pygame.image.load("assets/bg.png").convert()
      and blit them here.
    """
    play_rect = pygame.Rect(0, 0, WIDTH, HEIGHT - DIALOGUE_H)
    pygame.draw.rect(screen, COLOR_STAGE, play_rect)

    # "Background" stripes for a retro vibe
    stripe_h = 18
    for i in range(0, play_rect.height, stripe_h):
        c = (COLOR_STAGE[0] + (i // stripe_h) % 2 * 6,
             COLOR_STAGE[1] + (i // stripe_h) % 2 * 6,
             COLOR_STAGE[2] + (i // stripe_h) % 2 * 6)
        pygame.draw.rect(screen, c, (0, i, WIDTH, stripe_h))

    # Stage header
    # (We keep this minimal; main info is in dialogue box)
    # Placeholder "sprites"
    if show_leader:
        leader_rect = pygame.Rect(80, play_rect.height - 220, 180, 200)
        pygame.draw.rect(screen, (40, 70, 90), leader_rect, border_radius=10)
        label = pygame.font.Font(None, 28).render("이사님", True, COLOR_TEXT)
        screen.blit(label, (leader_rect.x + 55, leader_rect.y + 85))

    if show_trainer:
        trainer_rect = pygame.Rect(WIDTH - 260, play_rect.height - 220, 180, 200)
        pygame.draw.rect(screen, (70, 60, 120), trainer_rect, border_radius=10)
        label = pygame.font.Font(None, 28).render("신입", True, COLOR_TEXT)
        screen.blit(label, (trainer_rect.x + 65, trainer_rect.y + 85))

    # Stage info as subtle overlay
    if stage_title:
        overlay_font = pygame.font.Font(None, 26)
        t1 = overlay_font.render(stage_title, True, COLOR_MUTED)
        t2 = pygame.font.Font(None, 22).render(stage_subtitle or "", True, COLOR_MUTED)
        screen.blit(t1, (PADDING, PADDING))
        screen.blit(t2, (PADDING, PADDING + 26))

# =========================
# Dialogue / UI
# =========================
def draw_dialogue_ui(screen, font_base, font_small, speaker, body_lines, footer_lines, state_color=None):
    """
    Pokemon-style bottom dialogue box with speaker name, body text, and footer.
    """
    box_rect = pygame.Rect(PADDING, HEIGHT - DIALOGUE_H + PADDING, WIDTH - PADDING * 2, DIALOGUE_H - PADDING * 2)
    draw_box(screen, box_rect, COLOR_BOX, COLOR_BORDER, border_thickness=3, radius=14)

    # Speaker name
    name_color = state_color if state_color else COLOR_MUTED
    name_img = font_small.render(speaker, True, name_color)
    screen.blit(name_img, (box_rect.x + 14, box_rect.y + 10))

    # Body text
    max_w = box_rect.width - 28
    body_y = box_rect.y + 42
    draw_text_lines(screen, body_lines, font_base, COLOR_TEXT, box_rect.x + 14, body_y, line_gap=6)

    # Footer (controls / choices hint)
    if footer_lines:
        footer_y = box_rect.bottom - 52
        draw_text_lines(screen, footer_lines, font_small, COLOR_MUTED, box_rect.x + 14, footer_y, line_gap=4)

# =========================
# State Machine (Functional)
# =========================
def reset_game():
    """
    Returns a dict of all game state so we avoid OOP and keep it understandable.
    """
    return {
        "mode": "INTRO",          # INTRO, STAGE, FEEDBACK, GAME_OVER, CLEAR
        "intro_index": 0,         # which intro line
        "stage_index": 0,         # current stage
        "feedback": None,         # ("good"/"bad", message)
        "await_choice": False,    # if in stage and choices active
        "last_result": None,      # track last correctness
    }

def advance_intro(state):
    state["intro_index"] += 1
    if state["intro_index"] >= len(INTRO_LINES):
        state["mode"] = "STAGE"
        state["await_choice"] = True
    return state

def current_stage(state):
    return STAGES[state["stage_index"]]

def handle_choice(state, choice_num):
    """
    choice_num is 1/2/3 from key press.
    """
    st = current_stage(state)
    chosen_idx = choice_num - 1
    correct = (chosen_idx == st["correct_index"])

    if correct:
        state["mode"] = "FEEDBACK"
        state["feedback"] = ("good", MSG_CORRECT)
        state["last_result"] = True
    else:
        state["mode"] = "FEEDBACK"
        state["feedback"] = ("bad", MSG_WRONG)
        state["last_result"] = False
    state["await_choice"] = False
    return state

def advance_after_feedback(state):
    """
    After showing '효과는...' or '고객이 떠났습니다...' for ENTER,
    move to next stage or game over.
    """
    if state["last_result"] is True:
        # go next stage or clear
        state["stage_index"] += 1
        if state["stage_index"] >= len(STAGES):
            state["mode"] = "CLEAR"
        else:
            state["mode"] = "STAGE"
            state["await_choice"] = True
    else:
        state["mode"] = "GAME_OVER"
    state["feedback"] = None
    return state

# =========================
# Rendering per Mode
# =========================
def render_intro(screen, fonts, state):
    font_base, font_small, _font_big = fonts
    speaker, line = INTRO_LINES[state["intro_index"]]
    body_lines = wrap_text(line, font_base, WIDTH - PADDING * 2 - 60)

    footer = ["ENTER/SPACE: 다음   ESC: 종료"]
    draw_scene_placeholders(
        screen,
        stage_title="INTRO",
        stage_subtitle="Onboarding - CXJ Mission Briefing",
        show_leader=True,
        show_trainer=False,
    )
    draw_dialogue_ui(screen, font_base, font_small, speaker, body_lines, footer)

def render_stage(screen, fonts, state):
    font_base, font_small, _font_big = fonts
    st = current_stage(state)

    speaker = "CXJ 배틀"
    q = st["question"]
    body_lines = wrap_text(q, font_base, WIDTH - PADDING * 2 - 60)

    choices = st["choices"]
    footer = [
        f"1) {choices[0]}",
        f"2) {choices[1]}",
        f"3) {choices[2]}",
        "1/2/3: 선택   ESC: 종료"
    ]

    draw_scene_placeholders(
        screen,
        stage_title=st["title"],
        stage_subtitle=st["subtitle"],
        show_leader=False,
        show_trainer=True,
    )

    draw_dialogue_ui(screen, font_base, font_small, speaker, body_lines, footer)

def render_feedback(screen, fonts, state):
    font_base, font_small, _font_big = fonts
    kind, msg = state["feedback"]
    speaker = "SYSTEM"

    body_lines = wrap_text(msg, font_base, WIDTH - PADDING * 2 - 60)
    footer = ["ENTER/SPACE: 계속   ESC: 종료"]

    color = COLOR_GOOD if kind == "good" else COLOR_BAD

    # show both placeholders for "battle vibe"
    st_title = ""
    st_sub = ""
    if state["stage_index"] < len(STAGES):
        st = STAGES[state["stage_index"]]
        st_title, st_sub = st["title"], st["subtitle"]

    draw_scene_placeholders(
        screen,
        stage_title=st_title,
        stage_subtitle=st_sub,
        show_leader=True,
        show_trainer=True,
    )

    draw_dialogue_ui(screen, font_base, font_small, speaker, body_lines, footer, state_color=color)

def render_game_over(screen, fonts, state):
    font_base, font_small, font_big = fonts
    draw_scene_placeholders(
        screen,
        stage_title="GAME OVER",
        stage_subtitle="Customer Lost",
        show_leader=False,
        show_trainer=True,
    )

    # Big message in play area
    big = font_big.render(MSG_WRONG, True, COLOR_BAD)
    screen.blit(big, (PADDING, 120))

    body_lines = wrap_text("R을 눌러 처음부터 다시 도전하세요.", font_base, WIDTH - PADDING * 2 - 60)
    footer = ["R: 재시작   ESC: 종료"]

    draw_dialogue_ui(screen, font_base, font_small, "SYSTEM", body_lines, footer, state_color=COLOR_BAD)

def render_clear(screen, fonts, state):
    font_base, font_small, font_big = fonts
    draw_scene_placeholders(
        screen,
        stage_title="CLEAR!",
        stage_subtitle="CXJ Master",
        show_leader=True,
        show_trainer=True,
    )

    big = font_big.render(MSG_CLEAR, True, COLOR_GOOD)
    screen.blit(big, (PADDING, 120))

    body_lines = wrap_text("R을 눌러 다시 플레이하거나, ESC로 종료하세요.", font_base, WIDTH - PADDING * 2 - 60)
    footer = ["R: 재시작   ESC: 종료"]
    draw_dialogue_ui(screen, font_base, font_small, "SYSTEM", body_lines, footer, state_color=COLOR_GOOD)

# =========================
# Main Loop
# =========================
def main():
    pygame.init()
    pygame.display.set_caption("KIA CXJ Quest (Pygame)")
    screen = pygame.display.set_mode((WIDTH, HEIGHT))
    clock = pygame.time.Clock()
    fonts = load_fonts()

    state = reset_game()

    running = True
    while running:
        dt = clock.tick(FPS)

        # Events
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    running = False

                # Restart
                if event.key == pygame.K_r and state["mode"] in ("GAME_OVER", "CLEAR"):
                    state = reset_game()

                # Advance (Enter/Space)
                if event.key in (pygame.K_RETURN, pygame.K_SPACE):
                    if state["mode"] == "INTRO":
                        state = advance_intro(state)
                    elif state["mode"] == "FEEDBACK":
                        state = advance_after_feedback(state)
                    elif state["mode"] == "STAGE":
                        # In stage, Enter doesn't do anything (must pick 1/2/3)
                        pass

                # Choices (1/2/3)
                if state["mode"] == "STAGE" and state["await_choice"]:
                    if event.key == pygame.K_1:
                        state = handle_choice(state, 1)
                    elif event.key == pygame.K_2:
                        state = handle_choice(state, 2)
                    elif event.key == pygame.K_3:
                        state = handle_choice(state, 3)

        # Render
        screen.fill(COLOR_BG)

        if state["mode"] == "INTRO":
            render_intro(screen, fonts, state)
        elif state["mode"] == "STAGE":
            render_stage(screen, fonts, state)
        elif state["mode"] == "FEEDBACK":
            render_feedback(screen, fonts, state)
        elif state["mode"] == "GAME_OVER":
            render_game_over(screen, fonts, state)
        elif state["mode"] == "CLEAR":
            render_clear(screen, fonts, state)

        pygame.display.flip()

    pygame.quit()
    sys.exit(0)

if __name__ == "__main__":
    main()
